/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Mappers from "../models/apiMappers";
import * as Parameters from "../models/parameters";
import { DoverOnsiteCodingChallengeBackendAPIContext } from "../doverOnsiteCodingChallengeBackendAPIContext";

/** Class representing a Api. */
export class Api {
  private readonly client: DoverOnsiteCodingChallengeBackendAPIContext;

  /**
   * Create a Api.
   * @param {DoverOnsiteCodingChallengeBackendAPIContext} client Reference to the service client.
   */
  constructor(client: DoverOnsiteCodingChallengeBackendAPIContext) {
    this.client = client;
  }

  /**
   * A simple ViewSet for viewing and editing outreach.
   * @param id A UUID string identifying this outreach.
   * @param [options] The optional parameters
   * @returns Promise<msRest.RestResponse>
   */
  deleteMethod(id: string, options?: msRest.RequestOptionsBase): Promise<msRest.RestResponse>;
  /**
   * @param id A UUID string identifying this outreach.
   * @param callback The callback
   */
  deleteMethod(id: string, callback: msRest.ServiceCallback<void>): void;
  /**
   * @param id A UUID string identifying this outreach.
   * @param options The optional parameters
   * @param callback The callback
   */
  deleteMethod(id: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<void>): void;
  deleteMethod(id: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<void>, callback?: msRest.ServiceCallback<void>): Promise<msRest.RestResponse> {
    return this.client.sendOperationRequest(
      {
        id,
        options
      },
      deleteMethodOperationSpec,
      callback);
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const deleteMethodOperationSpec: msRest.OperationSpec = {
  httpMethod: "DELETE",
  path: "api/outreach/{id}",
  urlParameters: [
    Parameters.id
  ],
  responses: {
    204: {},
    default: {}
  },
  serializer
};
