/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import * as msRest from "@azure/ms-rest-js";


export const Outreach: msRest.CompositeMapper = {
  serializedName: "Outreach",
  type: {
    name: "Composite",
    className: "Outreach",
    modelProperties: {
      id: {
        readOnly: true,
        serializedName: "id",
        type: {
          name: "Uuid"
        }
      },
      created: {
        readOnly: true,
        serializedName: "created",
        type: {
          name: "DateTime"
        }
      },
      modified: {
        readOnly: true,
        serializedName: "modified",
        type: {
          name: "DateTime"
        }
      },
      editorState: {
        nullable: true,
        serializedName: "editor_state",
        type: {
          name: "Object"
        }
      },
      state: {
        serializedName: "state",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ListOutreachOKResponse: msRest.CompositeMapper = {
  serializedName: "ListOutreachOKResponse",
  type: {
    name: "Composite",
    className: "ListOutreachOKResponse",
    modelProperties: {
      count: {
        required: true,
        serializedName: "count",
        type: {
          name: "Number"
        }
      },
      next: {
        nullable: true,
        serializedName: "next",
        type: {
          name: "String"
        }
      },
      previous: {
        nullable: true,
        serializedName: "previous",
        type: {
          name: "String"
        }
      },
      results: {
        required: true,
        serializedName: "results",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "Outreach"
            }
          }
        }
      }
    }
  }
};
